#!flask/bin/python
from flask import Flask, jsonify, abort, request, make_response, url_for


app = Flask(__name__)

databases = [
{"country" : "afghanistan","city" : "kabul"},
{"country" : "albania","city" : "tirana"},
{"country" : "algeria","city" : "alger"},
{"country" : "american samoa","city" : "fagatogo"},
{"country" : "andorra","city" : "andorra la vella"},
{"country" : "angola","city" : "luanda"},
{"country" : "anguilla","city" : "the valley"},
{"country" : "antigua and barbuda","city" : "saint john's"},
{"country" : "argentina","city" : "buenos aires"},
{"country" : "armenia","city" : "yerevan"},
{"country" : "aruba","city" : "oranjestad"},
{"country" : "australia","city" : "canberra"},
{"country" : "austria","city" : "Wien"},
{"country" : "azerbaijan","city" : "baku"},
{"country" : "bahamas","city" : "nassau"},
{"country" : "bahrain","city" : "al-manama"},
{"country" : "bangladesh","city" : "dhaka"},
{"country" : "barbados","city" : "bridgetown"},
{"country" : "belarus","city" : "minsk"},
{"country" : "belgium","city" : "bruxelles [brussel]"},
{"country" : "belize","city" : "belmopan"},
{"country" : "benin","city" : "porto-novo"},
{"country" : "bermuda","city" : "hamilton"},
{"country" : "bhutan","city" : "thimphu"},
{"country" : "bolivia","city" : "la paz"},
{"country" : "bosnia and herzegovina","city" : "sarajevo"},
{"country" : "botswana","city" : "gaborone"},
{"country" : "brazil","city" : "brasilia"},
{"country" : "brunei","city" : "bandar seri begawan"},
{"country" : "bulgaria","city" : "sofia"},
{"country" : "burkina faso","city" : "ouagadougou"},
{"country" : "burundi","city" : "bujumbura"},
{"country" : "cambodia","city" : "phnom penh"},
{"country" : "cameroon","city" : "yaound"},
{"country" : "canada","city" : "ottawa"},
{"country" : "cape verde","city" : "praia"},
{"country" : "cayman islands","city" : "george town"},
{"country" : "central african republic","city" : "bangui"},
{"country" : "chad","city" : "n'djam"},
{"country" : "chile","city" : "santiago de chile"},
{"country" : "china","city" : "peking"},
{"country" : "christmas island","city" : "flying fish cove"},
{"country" : "cocos (keeling) islands","city" : "West island"},
{"country" : "colombia","city" : "santaf"},
{"country" : "comoros","city" : "moroni"},
{"country" : "congo","city" : "brazzaville"},
{"country" : "congo, the democratic republic of the","city" : "kinshasa"},
{"country" : "cook islands","city" : "avarua"},
{"country" : "costa rica","city" : "san jos"},
{"country" : "ivory coast","city" : "yamoussoukro"},
{"country" : "croatia","city" : "zagreb"},
{"country" : "cuba","city" : "la habana"},
{"country" : "cyprus","city" : "nicosia"},
{"country" : "czech republic","city" : "praha"},
{"country" : "denmark","city" : "copenhagen"},
{"country" : "djibouti","city" : "djibouti"},
{"country" : "dominica","city" : "roseau"},
{"country" : "dominican republic","city" : "santo domingo de guzm"},
{"country" : "east timor","city" : "dili"},
{"country" : "ecuador","city" : "quito"},
{"country" : "egypt","city" : "cairo"},
{"country" : "england","city" : "london"},
{"country" : "el salvador","city" : "san salvador"},
{"country" : "equatorial guinea","city" : "malabo"},
{"country" : "eritrea","city" : "asmara"},
{"country" : "estonia","city" : "tallinn"},
{"country" : "ethiopia","city" : "addis abeba"},
{"country" : "falkland islands","city" : "stanley"},
{"country" : "faroe islands","city" : "torshavn"},
{"country" : "fiji islands","city" : "suva"},
{"country" : "finland","city" : "helsinki [helsingfors]"},
{"country" : "france","city" : "paris"},
{"country" : "french guiana","city" : "cayenne"},
{"country" : "french polynesia","city" : "papeete"},
{"country" : "gabon","city" : "libreville"},
{"country" : "gambia","city" : "banjul"},
{"country" : "georgia","city" : "tbilisi"},
{"country" : "germany","city" : "berlin"},
{"country" : "ghana","city" : "accra"},
{"country" : "gibraltar","city" : "gibraltar"},
{"country" : "greece","city" : "athenai"},
{"country" : "greenland","city" : "nuuk"},
{"country" : "grenada","city" : "saint george's"},
{"country" : "guadeloupe","city" : "basse-terre"},
{"country" : "guam","city" : "aga"},
{"country" : "guatemala","city" : "ciudad de guatemala"},
{"country" : "guinea","city" : "conakry"},
{"country" : "guinea-bissau","city" : "bissau"},
{"country" : "guyana","city" : "georgetown"},
{"country" : "haiti","city" : "port-au-prince"},
{"country" : "holy see (vatican city state)","city" : "citt"},
{"country" : "honduras","city" : "tegucigalpa"},
{"country" : "hong kong","city" : "victoria"},
{"country" : "hungary","city" : "budapest"},
{"country" : "iceland","city" : "reykjav"},
{"country" : "india","city" : "new delhi"},
{"country" : "indonesia","city" : "jakarta"},
{"country" : "iran","city" : "tehran"},
{"country" : "iraq","city" : "baghdad"},
{"country" : "ireland","city" : "dublin"},
{"country" : "israel","city" : "jerusalem"},
{"country" : "italy","city" : "roma"},
{"country" : "jamaica","city" : "kingston"},
{"country" : "japan","city" : "tokyo"},
{"country" : "jordan","city" : "amman"},
{"country" : "kazakstan","city" : "astana"},
{"country" : "kenya","city" : "nairobi"},
{"country" : "kiribati","city" : "bairiki"},
{"country" : "kuwait","city" : "kuwait"},
{"country" : "kyrgyzstan","city" : "bishkek"},
{"country" : "laos","city" : "vientiane"},
{"country" : "latvia","city" : "riga"},
{"country" : "lebanon","city" : "beirut"},
{"country" : "lesotho","city" : "maseru"},
{"country" : "liberia","city" : "monrovia"},
{"country" : "libyan arab jamahiriya","city" : "tripoli"},
{"country" : "liechtenstein","city" : "vaduz"},
{"country" : "lithuania","city" : "vilnius"},
{"country" : "luxembourg","city" : "luxembourg [luxemburg/l"},
{"country" : "macao","city" : "macao"},
{"country" : "macedonia","city" : "skopje"},
{"country" : "madagascar","city" : "antananarivo"},
{"country" : "malawi","city" : "lilongwe"},
{"country" : "malaysia","city" : "kuala lumpur"},
{"country" : "maldives","city" : "male"},
{"country" : "mali","city" : "bamako"},
{"country" : "malta","city" : "valletta"},
{"country" : "marshall islands","city" : "dalap-uliga-darrit"},
{"country" : "martinique","city" : "fort-de-france"},
{"country" : "mauritania","city" : "nouakchott"},
{"country" : "mauritius","city" : "port-louis"},
{"country" : "mayotte","city" : "mamoutzou"},
{"country" : "mexico","city" : "ciudad de m"},
{"country" : "micronesia, federated states of","city" : "palikir"},
{"country" : "moldova","city" : "chisinau"},
{"country" : "monaco","city" : "monaco-ville"},
{"country" : "mongolia","city" : "ulan bator"},
{"country" : "montserrat","city" : "plymouth"},
{"country" : "morocco","city" : "rabat"},
{"country" : "mozambique","city" : "maputo"},
{"country" : "myanmar","city" : "rangoon (yangon)"},
{"country" : "namibia","city" : "Windhoek"},
{"country" : "nauru","city" : "yaren"},
{"country" : "nepal","city" : "kathmandu"},
{"country" : "netherlands","city" : "amsterdam"},
{"country" : "netherlands antilles","city" : "Willemstad"},
{"country" : "new caledonia","city" : "noum"},
{"country" : "new zealand","city" : "Wellington"},
{"country" : "nicaragua","city" : "managua"},
{"country" : "niger","city" : "niamey"},
{"country" : "nigeria","city" : "abuja"},
{"country" : "niue","city" : "alofi"},
{"country" : "norfolk island","city" : "kingston"},
{"country" : "north korea","city" : "pyongyang"},
{"country" : "northern ireland","city" : "belfast"},
{"country" : "northern mariana islands","city" : "garapan"},
{"country" : "norway","city" : "oslo"},
{"country" : "oman","city" : "masqat"},
{"country" : "pakistan","city" : "islamabad"},
{"country" : "palau","city" : "koror"},
{"country" : "palestine","city" : "gaza"},
{"country" : "panama","city" : "ciudad de panam"},
{"country" : "papua new guinea","city" : "port moresby"},
{"country" : "paraguay","city" : "asunci"},
{"country" : "peru","city" : "lima"},
{"country" : "philippines","city" : "manila"},
{"country" : "pitcairn","city" : "adamstown"},
{"country" : "poland","city" : "Warszawa"},
{"country" : "portugal","city" : "lisboa"},
{"country" : "puerto rico","city" : "san juan"},
{"country" : "qatar","city" : "doha"},
{"country" : "reunion","city" : "saint-denis"},
{"country" : "romania","city" : "bucuresti"},
{"country" : "russian federation","city" : "moscow"},
{"country" : "rwanda","city" : "kigali"},
{"country" : "saint helena","city" : "jamestown"},
{"country" : "saint kitts and nevis","city" : "basseterre"},
{"country" : "saint lucia","city" : "castries"},
{"country" : "saint pierre and miquelon","city" : "saint-pierre"},
{"country" : "saint vincent and the grenadines","city" : "kingstown"},
{"country" : "samoa","city" : "apia"},
{"country" : "san marino","city" : "san marino"},
{"country" : "sao tome and principe","city" : "s"},
{"country" : "saudi arabia","city" : "riyadh"},
{"country" : "scotland","city" : "edinburgh"},
{"country" : "senegal","city" : "dakar"},
{"country" : "seychelles","city" : "victoria"},
{"country" : "sierra leone","city" : "freetown"},
{"country" : "singapore","city" : "singapore"},
{"country" : "slovakia","city" : "bratislava"},
{"country" : "slovenia","city" : "ljubljana"},
{"country" : "solomon islands","city" : "honiara"},
{"country" : "somalia","city" : "mogadishu"},
{"country" : "south africa","city" : "pretoria"},
{"country" : "south korea","city" : "seoul"},
{"country" : "south sudan","city" : "juba"},
{"country" : "spain","city" : "madrid"},
{"country" : "sri lanka","city" : "colombo"},
{"country" : "sudan","city" : "khartum"},
{"country" : "suriname","city" : "paramaribo"},
{"country" : "svalbard and jan mayen","city" : "longyearbyen"},
{"country" : "swaziland","city" : "mbabane"},
{"country" : "sweden","city" : "stockholm"},
{"country" : "switzerland","city" : "bern"},
{"country" : "syria","city" : "damascus"},
{"country" : "taiwan","city" : "taipei"},
{"country" : "tajikistan","city" : "dushanbe"},
{"country" : "tanzania","city" : "dodoma"},
{"country" : "thailand","city" : "bangkok"},
{"country" : "togo","city" : "lom"},
{"country" : "tokelau","city" : "fakaofo"},
{"country" : "tonga","city" : "nuku'alofa"},
{"country" : "trinidad and tobago","city" : "port-of-spain"},
{"country" : "tunisia","city" : "tunis"},
{"country" : "turkey","city" : "ankara"},
{"country" : "turkmenistan","city" : "ashgabat"},
{"country" : "turks and caicos islands","city" : "cockburn town"},
{"country" : "tuvalu","city" : "funafuti"},
{"country" : "uganda","city" : "kampala"},
{"country" : "ukraine","city" : "kyiv"},
{"country" : "united arab emirates","city" : "abu dhabi"},
{"country" : "united kingdom","city" : "london"},
{"country" : "united states","city" : "Washington"},
{"country" : "uruguay","city" : "montevideo"},
{"country" : "uzbekistan","city" : "toskent"},
{"country" : "vanuatu","city" : "port-vila"},
{"country" : "venezuela","city" : "caracas"},
{"country" : "vietnam","city" : "hanoi"},
{"country" : "virgin islands, british","city" : "road town"},
{"country" : "virgin islands, u.s.","city" : "charlotte amalie"},
{"country" : "Wales","city" : "cardiff"},
{"country" : "Wallis and futuna","city" : "mata-utu"},
{"country" : "Western sahara","city" : "el-aai"},
{"country" : "yemen","city" : "sanaa"},
{"country" : "yugoslavia","city" : "beograd"},
{"country" : "zambia","city" : "lusaka"},
{"country" : "zimbabwe","city" : "harare"}
]

@app.errorhandler(404)
def not_found(error):
    return make_response(jsonify({'error': 'not found'}), 404)

@app.route('/pythonpro/demo/v1.0/country=<string:database_title>', methods=['get'])
def get_database(database_title):
    country = database_title.lower()
    database = [database for database in databases if database['country'] == country]
    if len(database) == 0:
        abort(404)
    return jsonify({'database': database[0]})

if __name__ == '__main__':
    app.run(debug=True)